language: go
sudo: false
go:
  - 1.x
install:
  - go mod download
  - curl https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | BINDIR=$GOPATH/bin sh
script:
  - golangci-lint run --enable-all -D errcheck -D lll -D dupl -D gochecknoglobals --deadline 5m
  - go test -v -coverprofile=coverage.txt -covermode=atomic ./...
after_success:
  - bash <(curl -s https://codecov.io/bash)
env:
  global:
    - GO111MODULE=on
    - GOPROXY=https://proxy.golang.org
