language: go
sudo: false
go:
  - 1.x
  - tip
install:
  - go mod download
  - go get github.com/golangci/golangci-lint/cmd/golangci-lint@master
script:
  - golangci-lint run --enable-all -D errcheck -D lll -D dupl -D gochecknoglobals --deadline 5m
  - go test -v -coverprofile=coverage.txt -covermode=atomic
after_success:
  - bash <(curl -s https://codecov.io/bash)
env:
  - GO111MODULE=on
